spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/niuke?serverTimezone=UTC
    username: root
    password: 862624436
  thymeleaf:
    cache: false
logging:
  level:
    community: debug
  file:
    path: d:/work/data/nowcoder/community